### ISSUE TITLE
Create SUT scripts for Linux vm's

### ISSUE THREAD

**Issue by jpsider** [BelayTechnologies/Belay-Device#113]
This is similar to #110 - but these are typically used during a test case.  I have create the shell of all the scripts here:
Belay-Device-Code\sut-scripts\LINUX

**Comment by jtlitch** [comment]
I was able to get the basics done for the coinflip and firefox. I removed the screenshot, since not all Linux systems have a GUI. I did not test the firefox installer since it was giving me some issues copying over to my vm (will work on that tomorrow evening).

**Comment by jpsider** [comment]
maybe we should focus less on firefox, and do apache instead?  I think that will be a better use case for building multi-machine tests for the next release.  :-)

**Comment by jpsider** [comment]
Done, created follow on ticket to clean up code #154
