### ISSUE TITLE
deviceManager.py does not run mulitple agents

### ISSUE THREAD

**Issue by jpsider** [BelayTechnologies/Belay-Device#3]
Currently it only supports 1 vm at a time.

That was my fault. I was running a Popen when I should have just done a check_output. Popen was being followed up with a poll() that waits until the process returns complete. check_output just blindly submits and checks for a return code from the shell.

**Comment by jtlitch** [comment]
Updated the code as it stands to run multiple agents through a multiprocessing pool. Most of this code can be reused, but this ticket will remain open until fully resolved.
