### ISSUE TITLE
Add Agent_Error as a color (UI only Ticket)

### ISSUE THREAD

**Issue by jpsider** [BelayTechnologies/Belay-Device#41]
Agent updates will be included in ticket #21

**Comment by jpsider** [comment]
Color has been added. It can be changed if it offends anyone!

**Comment by jmeetre** [comment]
Justin's new nickname: The Closer.

**Comment by jpsider** [comment]
new?

On Wed, Oct 7, 2015 at 8:05 AM, jmeetre <notifications@github.com> wrote:

> Justin's new nickname: The Closer.
> On Oct 6, 2015 7:51 PM, "Justin Sider" <notifications@github.com> wrote:
>
> > Closed #41 <https://github.com/BelayTechnologies/Belay-Device/issues/41
> >.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/BelayTechnologies/Belay-Device/issues/41#event-428591835
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BelayTechnologies/Belay-Device/issues/41#issuecomment-146176847>
> .
>



-- 
Thank you,

Justin Sider
Chief Information Officer
Belay Technologies
jsider@belaytech.com
(443) 598-2530
